<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAony/IFzcHnoYq9v+hR9l'."\n".'sh3ZFov5ir1GzD5l+J47h4pskSKsr3Zuziom2jMmEuvGDZkp4Wiv4bG/ysXoyo2h'."\n".'W7rQYv6lOnjksKCV+6sgDMfwqeEkreNakxrSmDhCMptH9CLSIcs58iLFrih9ZKXU'."\n".'6yaDFFeUTUIk/ixeamnKjrGDLQo/II9+vv42nCyuiOyZxXhHTRoDEPZ0gTGh2R9S'."\n".'tSZTDM2IHBBmcwtUaYo4IERzUHjwkooIQBYeOHcsHCJHGi1DUQJobw9+jNEKon3s'."\n".'oGDKASTUSgdRaylvvn+62hEvIS3RCr8gFnuSZbcxNXjmFEA7E6MX/AA7FXDJdpQR'."\n".'CwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
