version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8801:8080

  casdoor:
    restart: always
    build:
      context: .
      dockerfile_inline: |
        FROM casbin/casdoor:2.37.0
        COPY ./conf /conf/
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8081:8000"
    depends_on:
      - db
    environment:
      driverName: "mysql"
      dataSourceName: 'root:123456@tcp(dbproxy:3306)/'

  db:
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      default:
        aliases:
          - dbproxy
      
