<script>
import { GlLoadingIcon, GlSprintf, GlLink } from '@gitlab/ui';
import { GlLineChart } from '@gitlab/ui/dist/charts';
import projectsHistoryQuery from 'ee/security_dashboard/graphql/queries/project_vulnerabilities_by_day_and_count.query.graphql';
import severitiesCountQuery from 'ee/security_dashboard/graphql/queries/vulnerability_severities_count.query.graphql';
import SecurityTrainingPromoBanner from 'ee/security_dashboard/components/project/security_training_promo_banner.vue';
import { PROJECT_LOADING_ERROR_MESSAGE, PdfExportError } from 'ee/security_dashboard/helpers';
import {
  DOC_PATH_PROJECT_SECURITY_DASHBOARD,
  EXPORT_ERROR_MESSAGE_CHART_LOADING,
  EXPORT_ERROR_MESSAGE_CHART_FAILURE,
} from 'ee/security_dashboard/constants';
import { createAlert } from '~/alert';
import PageHeading from '~/vue_shared/components/page_heading.vue';
import { formatDate, getDateInPast } from '~/lib/utils/datetime_utility';
import { s__, __ } from '~/locale';
import PdfExportButton from 'ee/security_dashboard/components/shared/pdf_export_button.vue';
import glFeatureFlagsMixin from '~/vue_shared/mixins/gl_feature_flags_mixin';

const CHART_DEFAULT_DAYS = 30;
const MAX_DAYS = 100;
const ISO_DATE = 'isoDate';
const SEVERITIES = [
  { key: 'critical', name: s__('severity|Critical'), color: '#660e00' },
  { key: 'high', name: s__('severity|High'), color: '#ae1800' },
  { key: 'medium', name: s__('severity|Medium'), color: '#9e5400' },
  { key: 'low', name: s__('severity|Low'), color: '#c17d10' },
  { key: 'info', name: s__('severity|Info'), color: '#428fdc' },
  { key: 'unknown', name: s__('severity|Unknown'), color: '#868686' },
];

export default {
  components: {
    SecurityTrainingPromoBanner,
    GlLoadingIcon,
    GlLineChart,
    GlSprintf,
    GlLink,
    PageHeading,
    PdfExportButton,
  },
  mixins: [glFeatureFlagsMixin()],
  props: {
    projectFullPath: {
      type: String,
      required: false,
      default: '',
    },
    shouldShowPromoBanner: {
      type: Boolean,
      required: true,
      default: true,
    },
  },
  apollo: {
    // up-do-date count of vulnerabilities by severity, used to show the most recent data point
    // eslint-disable-next-line @gitlab/vue-no-undef-apollo-properties
    todaysVulnerabilitiesCount: {
      query: severitiesCountQuery,
      variables() {
        return {
          fullPath: this.projectFullPath,
          isProject: true,
          state: ['DETECTED', 'CONFIRMED'],
        };
      },
      update({ project }) {
        return project.vulnerabilitySeveritiesCount;
      },
      error() {
        createAlert({ message: PROJECT_LOADING_ERROR_MESSAGE });
      },
    },
    // historical, trending data, which gets generated by a cron job
    trendsByDay: {
      query: projectsHistoryQuery,
      variables() {
        return {
          fullPath: this.projectFullPath,
          endDate: this.todaysDate,
          startDate: this.startDate,
        };
      },
      update({ project }) {
        return project.vulnerabilitiesCountByDay.nodes;
      },
      error() {
        createAlert({ message: PROJECT_LOADING_ERROR_MESSAGE });
      },
    },
  },
  data() {
    return {
      trendsByDay: [],
      chart: null,
    };
  },
  computed: {
    chartStartDate() {
      return formatDate(getDateInPast(new Date(), CHART_DEFAULT_DAYS), ISO_DATE);
    },
    startDate() {
      return formatDate(getDateInPast(new Date(), MAX_DAYS), ISO_DATE);
    },
    todaysDate() {
      return formatDate(new Date(), ISO_DATE);
    },
    trendsByDayWithMostRecentData() {
      const lastTrendEntry = this.trendsByDay.at(-1);

      const trendDataWithoutLastEntry = this.trendsByDay.slice(0, -1);
      const isLastTrendEntryFromToday = lastTrendEntry?.date === this.todaysDate;

      return [
        // if the last entry is from today, replace it with the most recent data. otherwise, just append it.
        ...(isLastTrendEntryFromToday ? trendDataWithoutLastEntry : this.trendsByDay),
        { ...this.todaysVulnerabilitiesCount, date: this.todaysDate },
      ];
    },
    dataSeries() {
      const series = SEVERITIES.map(({ key, name, color }) => ({
        key,
        name,
        data: [],
        itemStyle: {
          color,
        },
        lineStyle: {
          color,
        },
      }));

      this.trendsByDayWithMostRecentData.forEach((trend) => {
        const { date, ...severities } = trend;

        SEVERITIES.forEach(({ key }) => {
          series.find((s) => s.key === key).data.push([date, severities[key]]);
        });
      });

      return series;
    },
    isLoading() {
      return (
        this.$apollo.queries.trendsByDay.loading ||
        this.$apollo.queries.todaysVulnerabilitiesCount.loading
      );
    },
    chartOptions() {
      return {
        xAxis: {
          name: __('Date'),
          key: 'date',
          type: 'category',
        },
        yAxis: {
          name: __('Vulnerabilities'),
          key: 'vulnerabilities',
          type: 'value',
          minInterval: 1,
        },
        dataZoom: [
          {
            type: 'slider',
            startValue: this.chartStartDate,
          },
        ],
        toolbox: {
          show: true,
        },
      };
    },
  },
  methods: {
    onChartCreated(chart) {
      this.chart = chart;
    },
    getReportData() {
      if (this.isLoading) {
        throw new PdfExportError(EXPORT_ERROR_MESSAGE_CHART_LOADING);
      }

      if (!this.chart) {
        throw new PdfExportError(EXPORT_ERROR_MESSAGE_CHART_FAILURE);
      }

      return {
        project_vulnerabilities_history: {
          svg: this.chart.getDataURL({
            type: 'svg',
            excludeComponents: ['toolbox', 'dataZoom'],
          }),
        },
        full_path: this.projectFullPath,
      };
    },
  },
  i18n: {
    title: s__('SecurityReports|Security dashboard'),
    subtitle: s__(
      'SecurityReports|Historical view of open vulnerabilities in the default branch. Excludes vulnerabilities that were resolved or dismissed. %{linkStart}Learn more.%{linkEnd}',
    ),
  },
  DOC_PATH_PROJECT_SECURITY_DASHBOARD,
};
</script>

<template>
  <div>
    <security-training-promo-banner v-if="shouldShowPromoBanner" />

    <page-heading :heading="s__('SecurityReports|Security dashboard')">
      <template #description>
        <gl-sprintf
          :message="
            s__(
              'SecurityReports|Historical view of open vulnerabilities in the default branch. Excludes vulnerabilities that were resolved or dismissed. %{linkStart}Learn more.%{linkEnd}',
            )
          "
        >
          <template #link="{ content }">
            <gl-link :href="$options.DOC_PATH_PROJECT_SECURITY_DASHBOARD" target="_blank">{{
              content
            }}</gl-link>
          </template>
        </gl-sprintf>
      </template>
      <template #actions>
        <pdf-export-button
          v-if="glFeatures.vulnerabilitiesPdfExport"
          :get-report-data="getReportData"
        />
      </template>
    </page-heading>

    <div>
      <gl-loading-icon v-if="isLoading" size="lg" class="gl-mt-6" />
      <gl-line-chart
        v-else
        class="gl-mt-6"
        :data="dataSeries"
        :option="chartOptions"
        responsive
        :include-legend-avg-max="false"
        @created="onChartCreated"
      />
    </div>
  </div>
</template>
