services:        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8801:8080

  nodebb:
    build: .
    restart: unless-stopped
    ports:
      - '4567:4567' # comment this out if you don't want to expose NodeBB to the host, or change the first number to any port you want

  postgres:
    build:
      context: .
      dockerfile_inline: |
        FROM postgres:17.4-alpine
#        COPY ./_resources/nodebb.sql /docker-entrypoint-initdb.d/db.sql
    restart: unless-stopped
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    networks:
      default:
        aliases:
          - dbproxy

  redis:
    image: redis:7.4.3-alpine
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes', '--loglevel', 'warning']
    # command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"] # uncomment if you want to use snapshotting instead of AOF
    profiles:
      - redis
  
  mongo:
    build:
      context: .
      dockerfile_inline: |
        FROM mongo:7-jammy
        COPY ./install/docker/mongodb-user-init.js /docker-entrypoint-initdb.d/user-init.js
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodebb
      MONGO_INITDB_ROOT_PASSWORD: nodebb
      MONGO_INITDB_DATABASE: nodebb
