# frozen_string_literal: true

require 'fast_spec_helper'

RSpec.describe Gitlab::Llm::PromptVersions, feature_category: :ai_abstraction_layer do
  using RSpec::Parameterized::TableSyntax

  where(:prompt_name, :model_family, :expected_version) do
    "categorize_question" | nil | "^1.0.0"
    "chat/build_reader" | "amazon_q" | "^1.0.0"
    "chat/build_reader" | nil | "^1.0.0"
    "chat/build_reader" | "claude_3" | "^1.0.0"
    "chat/build_reader" | "mistral" | "^1.0.0"
    "chat/build_reader" | "mixtral" | "^1.0.0"
    "chat/commit_reader" | "amazon_q" | "^1.0.0"
    "chat/commit_reader" | nil | "^1.0.0"
    "chat/commit_reader" | "claude_3" | "^1.0.0"
    "chat/commit_reader" | "gpt" | "^1.0.0"
    "chat/commit_reader" | "mistral" | "^1.0.0"
    "chat/commit_reader" | "mixtral" | "^1.0.0"
    "chat/documentation_search" | "amazon_q" | "^1.0.0"
    "chat/documentation_search" | nil | "^1.0.0"
    "chat/documentation_search" | "claude_3" | "^1.0.0"
    "chat/documentation_search" | "gpt" | "^1.0.0"
    "chat/documentation_search" | "mistral" | "^1.0.0"
    "chat/documentation_search" | "mixtral" | "^1.0.0"
    "chat/epic_reader" | "amazon_q" | "^1.0.0"
    "chat/epic_reader" | nil | "^1.0.0"
    "chat/epic_reader" | "claude_3" | "^1.0.0"
    "chat/epic_reader" | "gpt" | "^1.0.0"
    "chat/epic_reader" | "mistral" | "^1.0.0"
    "chat/epic_reader" | "mixtral" | "^1.0.0"
    "chat/explain_code" | "amazon_q" | "^1.0.0"
    "chat/explain_code" | nil | "^1.0.0"
    "chat/explain_code" | "claude_3" | "^1.0.0"
    "chat/explain_code" | "gpt" | "^1.0.0"
    "chat/explain_code" | "mistral" | "^1.0.0"
    "chat/explain_code" | "mistral_nemo" | "^1.0.0"
    "chat/explain_code" | "mixtral" | "^1.0.0"
    "chat/explain_vulnerability" | "amazon_q" | "^1.0.0"
    "chat/explain_vulnerability" | nil | "^1.0.0"
    "chat/explain_vulnerability" | "claude_3" | "^1.0.0"
    "chat/explain_vulnerability" | "mistral" | "^1.0.0"
    "chat/explain_vulnerability" | "mixtral" | "^1.0.0"
    "chat/fix_code" | "amazon_q" | "^1.0.0"
    "chat/fix_code" | nil | "^1.0.0"
    "chat/fix_code" | "claude_3" | "^1.0.0"
    "chat/fix_code" | "gpt" | "^1.0.0"
    "chat/fix_code" | "mistral" | "^1.0.0"
    "chat/fix_code" | "mixtral" | "^1.0.0"
    "chat/issue_reader" | "amazon_q" | "^1.0.0"
    "chat/issue_reader" | nil | "^1.0.0"
    "chat/issue_reader" | "claude_3" | "^1.0.0"
    "chat/issue_reader" | "gpt" | "^1.0.0"
    "chat/issue_reader" | "mistral" | "^1.0.0"
    "chat/issue_reader" | "mixtral" | "^1.0.0"
    "chat/merge_request_reader" | "amazon_q" | "^1.0.0"
    "chat/merge_request_reader" | nil | "^1.0.0"
    "chat/merge_request_reader" | "claude_3" | "^1.0.0"
    "chat/merge_request_reader" | "mistral" | "^1.0.0"
    "chat/merge_request_reader" | "mixtral" | "^1.0.0"
    "chat/react" | "amazon_q" | "^1.0.0"
    "chat/react" | nil | "^1.0.0"
    "chat/react" | "claude_3" | "^1.0.0"
    "chat/react" | "gpt" | "^1.0.0"
    "chat/react" | "mistral" | "^1.0.0"
    "chat/react" | "mistral_nemo" | "^1.0.0"
    "chat/react" | "mixtral" | "^1.0.0"
    "chat/react" | "vertex" | "^1.0.0"
    "chat/refactor_code" | "amazon_q" | "^1.0.0"
    "chat/refactor_code" | nil | "^1.0.0"
    "chat/refactor_code" | "claude_3" | "^1.0.0"
    "chat/refactor_code" | "gpt" | "^1.0.0"
    "chat/refactor_code" | "mistral" | "^1.0.0"
    "chat/refactor_code" | "mixtral" | "^1.0.0"
    "chat/summarize_comments" | "amazon_q" | "^1.0.0"
    "chat/summarize_comments" | nil | "^1.0.0"
    "chat/summarize_comments" | "claude_3" | "^1.0.0"
    "chat/summarize_comments" | "mistral" | "^1.0.0"
    "chat/summarize_comments" | "mixtral" | "^1.0.0"
    "chat/troubleshoot_job" | "amazon_q" | "^1.0.0"
    "chat/troubleshoot_job" | nil | "^1.0.0"
    "chat/troubleshoot_job" | "claude_3" | "^1.0.0"
    "chat/troubleshoot_job" | "mistral" | "^1.0.0"
    "chat/troubleshoot_job" | "mixtral" | "^1.0.0"
    "chat/write_tests" | "amazon_q" | "^1.0.0"
    "chat/write_tests" | nil | "^1.0.0"
    "chat/write_tests" | "claude_3" | "^1.0.0"
    "chat/write_tests" | "gpt" | "^1.0.0"
    "chat/write_tests" | "mistral" | "^1.0.0"
    "chat/write_tests" | "mixtral" | "^1.0.0"
    "code_suggestions/completions" | "claude_3" | "^1.0.0"
    "code_suggestions/completions" | "codegemma" | "^1.0.0"
    "code_suggestions/completions" | "codellama" | "^1.0.0"
    "code_suggestions/completions" | "codestral" | "^1.0.0"
    "code_suggestions/completions" | "deepseekcoder" | "^1.0.0"
    "code_suggestions/completions" | "gpt" | "^1.0.0"
    "code_suggestions/completions" | "llama3" | "^1.0.0"
    "code_suggestions/completions" | "mistral" | "^1.0.0"
    "code_suggestions/completions" | "mixtral" | "^1.0.0"
    "code_suggestions/generations" | nil | "^2.0.1"
    "code_suggestions/generations" | "claude_3" | "^1.0.0"
    "code_suggestions/generations" | "codegemma" | "^1.0.0"
    "code_suggestions/generations" | "codellama" | "^1.0.0"
    "code_suggestions/generations" | "codestral" | "^1.0.0"
    "code_suggestions/generations" | "deepseekcoder" | "^1.0.0"
    "code_suggestions/generations" | "gpt" | "^1.0.0"
    "code_suggestions/generations" | "llama3" | "^1.0.0"
    "code_suggestions/generations" | "mistral" | "^1.0.0"
    "code_suggestions/generations" | "mixtral" | "^1.0.0"
    "generate_commit_message" | nil | "^1.0.0"
    "generate_description" | nil | "^1.0.0"
    "generate_description" | "claude_3" | "^1.0.0"
    "glab_ask_git_command" | nil | "^1.0.0"
    "measure_comment_temperature" | nil | "^1.0.0"
    "model_configuration/check" | "claude_3" | "^1.0.0"
    "model_configuration/check" | "codegemma" | "^1.0.0"
    "model_configuration/check" | "codellama" | "^1.0.0"
    "model_configuration/check" | "codestral" | "^1.0.0"
    "model_configuration/check" | "deepseekcoder" | "^1.0.0"
    "model_configuration/check" | "gpt" | "^1.0.0"
    "model_configuration/check" | "llama3" | "^1.0.0"
    "model_configuration/check" | "mistral" | "^1.0.0"
    "model_configuration/check" | "mistral_nemo" | "^1.0.0"
    "model_configuration/check" | "mixtral" | "^1.0.0"
    "resolve_vulnerability" | nil | "^1.0.0"
    "summarize_new_merge_request" | nil | "^2.0.0"
    "summarize_review" | nil | "^2.0.0"
  end

  with_them do
    it "returns the correct version for the prompt" do
      expect(described_class.version_for_prompt(prompt_name, model_family)).to eq expected_version
    end
  end
end
