<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR9RpbeX\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR9RpbeX/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR9RpbeX.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR9RpbeX\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerR9RpbeX\appAppKernelDevDebugContainer([
    'container.build_hash' => 'R9RpbeX',
    'container.build_id' => 'f6f2b6f3',
    'container.build_time' => 1735939706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR9RpbeX');
